### ISSUE TITLE
Should not throw with invalid gist url

### ISSUE THREAD

**Issue by turutupa** [GeorgeGkas/super-react-gist#2]
When providing a wrong gist URL it throws. It throws so bad that even when using a try-catch my app still crashes. I'm using this component so users can share gists so obviously I'll have to check that the url provided is correct, but nonetheless I think this should be handled better from the super-react-gist side.

**Comment by GeorgeGkas** [comment]
Hello,

We just released v1.1.0 that include features for error handling and better state management. Please take a look. If you need anything else, feel free to file a new issue.

Thank you for using this library! :)
